/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_register_design;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author gilmorer2
 */
public class Add_Form extends javax.swing.JFrame {

    /**
     * Creates new form Checking_Form
     */
    public Add_Form() {
        initComponents();
       // DisplayTable();
        setLocationRelativeTo(null);
        
      
        
        Border jpanel_title_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.blue);
       // set the border to the jPanel_title
        jPanel_title_checkings.setBorder(jpanel_title_border);
        
        Border glob_panel_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jPanel_checking.setBorder(glob_panel_border);
        
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_minimize_checking.setBorder(label_border);
        jLabel_close_checking.setBorder(label_border);
        
    }
    
    //display amount in checking
   /* private void DisplayTable()
            
            
            {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/banking_app", "root", "");
            String sql = "select * from banking";
            
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            jTable_savings.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
        /*    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel_checking = new javax.swing.JPanel();
        jLabel_close_checking = new javax.swing.JLabel();
        jLabel_minimize_checking = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel_title_checkings = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton_username = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_Username = new javax.swing.JTextField();
        jTextField_Sender = new javax.swing.JTextField();
        jTextField_Reciever = new javax.swing.JTextField();
        jTextField_Type = new javax.swing.JTextField();
        jTextField_Weight = new javax.swing.JTextField();
        jTextField_Status = new javax.swing.JTextField();
        jLabel_AdminPage = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel_checking.setBackground(new java.awt.Color(51, 204, 255));

        jLabel_close_checking.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_close_checking.setText(" X");
        jLabel_close_checking.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close_checking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_close_checkingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_close_checkingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_close_checkingMouseExited(evt);
            }
        });

        jLabel_minimize_checking.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_minimize_checking.setText(" -");
        jLabel_minimize_checking.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimize_checking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimize_checkingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_minimize_checkingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_minimize_checkingMouseExited(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jPanel_title_checkings.setBackground(new java.awt.Color(192, 192, 192));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Add");

        javax.swing.GroupLayout jPanel_title_checkingsLayout = new javax.swing.GroupLayout(jPanel_title_checkings);
        jPanel_title_checkings.setLayout(jPanel_title_checkingsLayout);
        jPanel_title_checkingsLayout.setHorizontalGroup(
            jPanel_title_checkingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_title_checkingsLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel_title_checkingsLayout.setVerticalGroup(
            jPanel_title_checkingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_title_checkingsLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_title_checkings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_title_checkings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText(" Home");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        jButton_username.setText("Upload");
        jButton_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_usernameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_usernameMouseExited(evt);
            }
        });
        jButton_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_usernameActionPerformed(evt);
            }
        });

        jLabel4.setText("Username:");

        jLabel6.setText("Sender Address:");

        jLabel7.setText("Reciever Address:");

        jLabel8.setText("Package Type:");

        jLabel9.setText("Weight:");

        jLabel10.setText("Status:");

        jTextField_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_UsernameActionPerformed(evt);
            }
        });

        jLabel_AdminPage.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_AdminPage.setText("Admin Page");
        jLabel_AdminPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_AdminPageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_AdminPageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_AdminPageMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addComponent(jLabel4)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_Username, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(jTextField_Sender)
                    .addComponent(jTextField_Reciever)
                    .addComponent(jTextField_Type)
                    .addComponent(jTextField_Weight)
                    .addComponent(jTextField_Status))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_username)
                            .addComponent(jLabel_AdminPage))))
                .addGap(0, 270, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextField_Sender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_Reciever, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_Weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jButton_username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jLabel_AdminPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(259, 259, 259))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_checkingLayout = new javax.swing.GroupLayout(jPanel_checking);
        jPanel_checking.setLayout(jPanel_checkingLayout);
        jPanel_checkingLayout.setHorizontalGroup(
            jPanel_checkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_checkingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_checkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_checkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_checkingLayout.createSequentialGroup()
                            .addComponent(jLabel_minimize_checking, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel_close_checking, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel_checkingLayout.setVerticalGroup(
            jPanel_checkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_checkingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_checkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_close_checking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_minimize_checking, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel_checking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_checking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_close_checkingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_close_checkingMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_close_checkingMouseClicked

   
    
    
    private void jLabel_close_checkingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_close_checkingMouseEntered

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_close_checking.setBorder(label_border);
        jLabel_close_checking.setForeground(Color.white);

    }//GEN-LAST:event_jLabel_close_checkingMouseEntered

    private void jLabel_close_checkingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_close_checkingMouseExited

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_close_checking.setBorder(label_border);
        jLabel_close_checking.setForeground(Color.black);

    }//GEN-LAST:event_jLabel_close_checkingMouseExited

    private void jLabel_minimize_checkingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimize_checkingMouseClicked

        this.setState(JFrame.ICONIFIED);

    }//GEN-LAST:event_jLabel_minimize_checkingMouseClicked

    private void jLabel_minimize_checkingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimize_checkingMouseEntered

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_minimize_checking.setBorder(label_border);
        jLabel_minimize_checking.setForeground(Color.white);

    }//GEN-LAST:event_jLabel_minimize_checkingMouseEntered

    private void jLabel_minimize_checkingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimize_checkingMouseExited

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_minimize_checking.setBorder(label_border);
        jLabel_minimize_checking.setForeground(Color.black);

    }//GEN-LAST:event_jLabel_minimize_checkingMouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        //go to the menu form
        Menu_Form mf = new Menu_Form();
        mf.setVisible(true);
        mf.pack();
        mf.setDefaultCloseOperation(Menu_Form.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        
        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(0,0,255));
        jLabel3.setBorder(label_border);
        
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        
        Border label_create_account_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.lightGray);
        jLabel3.setBorder(label_create_account_border);
        
    }//GEN-LAST:event_jLabel3MouseExited

    
    public boolean verifyFields()
    {
        String Username = jTextField_Username.getText();
        String SenderAddress = jTextField_Sender.getText();
        String RecieverAddress = jTextField_Reciever.getText();
        String PackageType = jTextField_Type.getText(); 
        String Weight = jTextField_Weight.getText();
        String Status = jTextField_Status.getText();
       
        // check empty fields
        if(Username.trim().equals("") )
        {
            JOptionPane.showMessageDialog(null, "Username field is empty","Empty Fields",2);
            return false;
        }
        
        if(SenderAddress.trim().equals("") )
        {
            JOptionPane.showMessageDialog(null, "Sender Address field is empty","Empty Fields",2);
            return false;
        }
        if(RecieverAddress.trim().equals("") )
        {
            JOptionPane.showMessageDialog(null, "Reciever Address field is empty","Empty Fields",2);
            return false;
        }
        if(PackageType.trim().equals("") )
        {
            JOptionPane.showMessageDialog(null, "Package field is empty","Empty Fields",2);
            return false;
        }
        if(Weight.trim().equals("") )
        {
            JOptionPane.showMessageDialog(null, "Weight field is empty","Empty Fields",2);
            return false;
        }
        if(Status.trim().equals("") )
        {
            JOptionPane.showMessageDialog(null, "Status field is empty","Empty Fields",2);
            return false;
        }
        
       
        
        // if everything is okay
        else{
            return true;
        }
        
    }
    // checks if username is registered in the database
    // has to check from the users database
    
    public boolean checkValid(String username){
        
        PreparedStatement st;
        ResultSet rs;
        boolean username_exist = false;
        
        
        //gets the username 
        String query = "SELECT * FROM `users` WHERE `Username` = ?";
        String user = jTextField_Username.getText();
        
        if (query != user) {
            JOptionPane.showMessageDialog(null, "This Username is Already Taken, Choose Another One", "Username Failed", 2);
        }
                   
        try {
            
            st = My_CNX.getConnection().prepareStatement(query);
            st.setString(1, username);
            rs = st.executeQuery();
            
            if(rs.next())
            {
                
                username_exist = false;
                JOptionPane.showMessageDialog(null, "This Username is Already Taken, Choose Another One", "Username Failed", 2);
            }
     
        } catch (SQLException ex) {
            Logger.getLogger(Register_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return username_exist;
    }
    
    
    
    //checks if username exists
    public boolean checkUsername(String username){
        
        PreparedStatement st;
        ResultSet rs;
        boolean username_exist = false;
        
        String query = "SELECT * FROM `package` WHERE `Username` = ?";
        String user = jTextField_Username.getText();
        
        // checks if the username actually exists
        if (query != user) {
            //username_exist = false;
                JOptionPane.showMessageDialog(null, "This username is connected to the database", "Invalid Username", 2);
        }
        
        try {
            
            st = My_CNX.getConnection().prepareStatement(query);
            st.setString(1, username);
            rs = st.executeQuery();
            
            if(rs.next())
            {
                username_exist = false;
                JOptionPane.showMessageDialog(null, "This Username is Already Taken, Choose Another One", "Username Failed", 2);
            }
     
        } catch (SQLException ex) {
            Logger.getLogger(Register_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return username_exist;
    }
    
    private void jButton_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_usernameActionPerformed
        // TODO add your handling code here:
      
        String tracking;
        //String tracking = jTextField_Package.getText();
        //String package = jTextField_Package.getText();
        
        String PackageID = UUID.randomUUID().toString();;
        String User = jTextField_Username.getText();
        String SenderAddress = jTextField_Sender.getText();
        String RecieverAddress = jTextField_Reciever.getText();
        String PackageType = jTextField_Type.getText(); 
        String Weight = jTextField_Weight.getText();
        String Status = jTextField_Status.getText();
               
        //String username = jTextField_Username.getText();
        
        if(verifyFields())
        {
            //if (!checkUsername(User))
            //{
                PreparedStatement ps;
                ResultSet rs;
                
               String registerUserQuery = "INSERT INTO `package`(`PackageID`, `Username`, `SenderAddress`, `ReceiverAddress`, `PackageType`, `Weight`, `Status` ) VALUES (?,?,?,?,?,?,?)";
                
                try {
                    ps = My_CNX.getConnection().prepareStatement(registerUserQuery);
                    ps.setString(1, PackageID);
                    ps.setString(2, User);
                    ps.setString(3, SenderAddress);
                    ps.setString(4, RecieverAddress);
                    ps.setString(5, PackageType);
                    ps.setString(6, Weight);
                    ps.setString(7, Status);
                    
                    //ps.setString(2, username);
                    
                   
                    
//                    try {
//                        // save the image as blob in the database
////                        if(image_path != null){
////                           
////                            InputStream image = new FileInputStream(new File(image_path));
////                            ps.setBlob(6, image);
////                            
////                        }
//                        
//                        //ps.setNull(7, java.sql.Types.NULL);
//                        ps.setString(7, tracking);
//                        
                        if(ps.executeUpdate() != 0){
                            JOptionPane.showMessageDialog(null, "The user has been added");
                        }else{
                            JOptionPane.showMessageDialog(null, "Error: Check Your Information");
                        }
//                        
//                    } catch (FileNotFoundException ex) {
//                        Logger.getLogger(Register_Form.class.getName()).log(Level.SEVERE, null, ex);
//                    }
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Register_Form.class.getName()).log(Level.SEVERE, null, ex);
                }
              
           // }    
        }
        
        
        
        
        

  
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton_usernameActionPerformed

    private void jButton_usernameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_usernameMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_usernameMouseEntered

    private void jButton_usernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_usernameMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_usernameMouseExited

    private void jTextField_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_UsernameActionPerformed

    
    
    
    
    private void jLabel_AdminPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_AdminPageMouseClicked
        // TODO add your handling code here:
        Admin_Form mf = new Admin_Form();
        mf.setVisible(true);
        mf.pack();
        mf.setDefaultCloseOperation(Admin_Form.EXIT_ON_CLOSE);
        this.dispose();        
    }//GEN-LAST:event_jLabel_AdminPageMouseClicked

    private void jLabel_AdminPageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_AdminPageMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(0,0,255));
        jLabel3.setBorder(label_border);        
    }//GEN-LAST:event_jLabel_AdminPageMouseEntered

    private void jLabel_AdminPageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_AdminPageMouseExited
        // TODO add your handling code here:
        Border label_create_account_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.lightGray);
        jLabel3.setBorder(label_create_account_border);
    }//GEN-LAST:event_jLabel_AdminPageMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_AdminPage;
    private javax.swing.JLabel jLabel_close_checking;
    private javax.swing.JLabel jLabel_minimize_checking;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_checking;
    private javax.swing.JPanel jPanel_title_checkings;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_Reciever;
    private javax.swing.JTextField jTextField_Sender;
    private javax.swing.JTextField jTextField_Status;
    private javax.swing.JTextField jTextField_Type;
    private javax.swing.JTextField jTextField_Username;
    private javax.swing.JTextField jTextField_Weight;
    // End of variables declaration//GEN-END:variables
}
